package cn.zucc.debug.macore.model.pojo;

public class DeviceAttrType extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr_type.c_id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr_type.c_devicetype_id
     *
     * @mbggenerated
     */
    private Integer devicetypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr_type.c_name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr_type.c_field_name
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr_type.c_label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr_type.c_data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr_type.c_id
     *
     * @return the value of t_device_attr_type.c_id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr_type.c_id
     *
     * @param id the value for t_device_attr_type.c_id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr_type.c_devicetype_id
     *
     * @return the value of t_device_attr_type.c_devicetype_id
     *
     * @mbggenerated
     */
    public Integer getDevicetypeId() {
        return devicetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr_type.c_devicetype_id
     *
     * @param devicetypeId the value for t_device_attr_type.c_devicetype_id
     *
     * @mbggenerated
     */
    public void setDevicetypeId(Integer devicetypeId) {
        this.devicetypeId = devicetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr_type.c_name
     *
     * @return the value of t_device_attr_type.c_name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr_type.c_name
     *
     * @param name the value for t_device_attr_type.c_name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr_type.c_field_name
     *
     * @return the value of t_device_attr_type.c_field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr_type.c_field_name
     *
     * @param fieldName the value for t_device_attr_type.c_field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr_type.c_label
     *
     * @return the value of t_device_attr_type.c_label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr_type.c_label
     *
     * @param label the value for t_device_attr_type.c_label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr_type.c_data_type
     *
     * @return the value of t_device_attr_type.c_data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr_type.c_data_type
     *
     * @param dataType the value for t_device_attr_type.c_data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", devicetypeId=").append(devicetypeId);
        sb.append(", name=").append(name);
        sb.append(", fieldName=").append(fieldName);
        sb.append(", label=").append(label);
        sb.append(", dataType=").append(dataType);
        sb.append("]");
        return sb.toString();
    }
}