package cn.zucc.debug.macore.model.pojo;

public class DeviceAttr extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr.c_id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr.c_device_id
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr.c_attrtype_id
     *
     * @mbggenerated
     */
    private Integer attrtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr.c_plc_address
     *
     * @mbggenerated
     */
    private String plcAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr.c_id
     *
     * @return the value of t_device_attr.c_id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr.c_id
     *
     * @param id the value for t_device_attr.c_id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr.c_device_id
     *
     * @return the value of t_device_attr.c_device_id
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr.c_device_id
     *
     * @param deviceId the value for t_device_attr.c_device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr.c_attrtype_id
     *
     * @return the value of t_device_attr.c_attrtype_id
     *
     * @mbggenerated
     */
    public Integer getAttrtypeId() {
        return attrtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr.c_attrtype_id
     *
     * @param attrtypeId the value for t_device_attr.c_attrtype_id
     *
     * @mbggenerated
     */
    public void setAttrtypeId(Integer attrtypeId) {
        this.attrtypeId = attrtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr.c_plc_address
     *
     * @return the value of t_device_attr.c_plc_address
     *
     * @mbggenerated
     */
    public String getPlcAddress() {
        return plcAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr.c_plc_address
     *
     * @param plcAddress the value for t_device_attr.c_plc_address
     *
     * @mbggenerated
     */
    public void setPlcAddress(String plcAddress) {
        this.plcAddress = plcAddress == null ? null : plcAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", attrtypeId=").append(attrtypeId);
        sb.append(", plcAddress=").append(plcAddress);
        sb.append("]");
        return sb.toString();
    }
}