package cn.zucc.debug.macore.model.pojo;

public class DeviceType extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_type.c_id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_type.c_name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_type.c_table_name
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_type.c_multi
     *
     * @mbggenerated
     */
    private Integer multi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_type.c_id
     *
     * @return the value of t_device_type.c_id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_type.c_id
     *
     * @param id the value for t_device_type.c_id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_type.c_name
     *
     * @return the value of t_device_type.c_name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_type.c_name
     *
     * @param name the value for t_device_type.c_name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_type.c_table_name
     *
     * @return the value of t_device_type.c_table_name
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_type.c_table_name
     *
     * @param tableName the value for t_device_type.c_table_name
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_type.c_multi
     *
     * @return the value of t_device_type.c_multi
     *
     * @mbggenerated
     */
    public Integer getMulti() {
        return multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_type.c_multi
     *
     * @param multi the value for t_device_type.c_multi
     *
     * @mbggenerated
     */
    public void setMulti(Integer multi) {
        this.multi = multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", tableName=").append(tableName);
        sb.append(", multi=").append(multi);
        sb.append("]");
        return sb.toString();
    }
}