package cn.zucc.debug.macore.model.pojo;

public class TerminalIp extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal_ip.c_id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal_ip.c_ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal_ip.c_port
     *
     * @mbggenerated
     */
    private Integer port;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal_ip.c_id
     *
     * @return the value of t_terminal_ip.c_id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal_ip.c_id
     *
     * @param id the value for t_terminal_ip.c_id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal_ip.c_ip
     *
     * @return the value of t_terminal_ip.c_ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal_ip.c_ip
     *
     * @param ip the value for t_terminal_ip.c_ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal_ip.c_port
     *
     * @return the value of t_terminal_ip.c_port
     *
     * @mbggenerated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal_ip.c_port
     *
     * @param port the value for t_terminal_ip.c_port
     *
     * @mbggenerated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_ip
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ip=").append(ip);
        sb.append(", port=").append(port);
        sb.append("]");
        return sb.toString();
    }
}