package cn.zucc.debug.macore.model.pojo;

public class Terminal extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.c_id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.c_object_id
     *
     * @mbggenerated
     */
    private Integer objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.c_code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.c_name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.c_port
     *
     * @mbggenerated
     */
    private Integer terminalIpId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.c_id
     *
     * @return the value of t_terminal.c_id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.c_id
     *
     * @param id the value for t_terminal.c_id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.c_object_id
     *
     * @return the value of t_terminal.c_object_id
     *
     * @mbggenerated
     */
    public Integer getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.c_object_id
     *
     * @param objectId the value for t_terminal.c_object_id
     *
     * @mbggenerated
     */
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.c_code
     *
     * @return the value of t_terminal.c_code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.c_code
     *
     * @param code the value for t_terminal.c_code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.c_name
     *
     * @return the value of t_terminal.c_name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.c_name
     *
     * @param name the value for t_terminal.c_name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getTerminalIpId() {
        return terminalIpId;
    }

    public void setTerminalIpId(Integer terminalIpId) {
        this.terminalIpId = terminalIpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", objectId=").append(objectId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}