package cn.zucc.debug.macore.model.mapper;

import cn.zucc.debug.frame.ssm.BaseMapper;
import cn.zucc.debug.macore.model.pojo.DBSql;

public interface DBSqlMapper extends BaseMapper<DBSql, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dbsql
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dbsql
     *
     * @mbggenerated
     */
    int insert(DBSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dbsql
     *
     * @mbggenerated
     */
    int insertSelective(DBSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dbsql
     *
     * @mbggenerated
     */
    DBSql selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dbsql
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dbsql
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DBSql record);
}