package cn.zucc.debug.macore.model.mapper;

import cn.zucc.debug.frame.ssm.BaseMapper;
import cn.zucc.debug.macore.model.pojo.DeviceAttrType;

public interface DeviceAttrTypeMapper extends BaseMapper<DeviceAttrType, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr_type
     *
     * @mbggenerated
     */
    int insert(DeviceAttrType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr_type
     *
     * @mbggenerated
     */
    int insertSelective(DeviceAttrType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr_type
     *
     * @mbggenerated
     */
    DeviceAttrType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceAttrType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceAttrType record);
}