package cn.zucc.debug.macore.model.mapper;

import cn.zucc.debug.frame.ssm.BaseMapper;
import cn.zucc.debug.macore.model.pojo.Device;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceMapper extends BaseMapper<Device, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_object_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_object_device
     *
     * @mbggenerated
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_object_device
     *
     * @mbggenerated
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_object_device
     *
     * @mbggenerated
     */
    Device selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_object_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_object_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Device record);

    List<Device> selectByObjectIdAndGroupId(@Param("objectId") Integer objectId, @Param("groupId") Integer groupId);

    List<Device> selectByObjectIdAndDevicetypeId(@Param("objectId") Integer objectId, @Param("devicetypeId") Integer devicetypeId);
}