package cn.zucc.debug.macore.model.mapper;

import cn.zucc.debug.frame.ssm.BaseMapper;
import cn.zucc.debug.macore.model.pojo.DeviceType;

public interface DeviceTypeMapper extends BaseMapper<DeviceType, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_type
     *
     * @mbggenerated
     */
    int insert(DeviceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_type
     *
     * @mbggenerated
     */
    int insertSelective(DeviceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_type
     *
     * @mbggenerated
     */
    DeviceType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceType record);
}