package cn.zucc.debug.macore.model.mapper;

import cn.zucc.debug.frame.ssm.BaseMapper;
import cn.zucc.debug.macore.model.pojo.Host;
import org.apache.ibatis.annotations.Param;

public interface HostMapper extends BaseMapper<Host, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_host
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_host
     *
     * @mbggenerated
     */
    int insert(Host record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_host
     *
     * @mbggenerated
     */
    int insertSelective(Host record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_host
     *
     * @mbggenerated
     */
    Host selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_host
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Host record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_host
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Host record);

    Host selectByIpAndAccountAndPassword(@Param("ip") String ip, @Param("port") Integer port, @Param("account") String account);
}