package cn.zucc.debug.macore.model.mapper;

import cn.zucc.debug.frame.ssm.BaseMapper;
import cn.zucc.debug.macore.model.pojo.Terminal;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TerminalMapper extends BaseMapper<Terminal, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated
     */
    int insert(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated
     */
    int insertSelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated
     */
    Terminal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Terminal record);

    Terminal selectByObjectIdAndCode(@Param("objectId") Integer objectId, @Param("code") String code);

    List<Terminal> selectByObjectId(@Param("objectId") Integer objectId);

    List<Terminal> selectByTerminalIpId(@Param("terminalIpId") Integer terminalIpId);
}