package cn.zucc.debug.macore.model.mapper;

import cn.zucc.debug.frame.ssm.BaseMapper;
import cn.zucc.debug.macore.model.pojo.TerminalIp;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TerminalIpMapper extends BaseMapper<TerminalIp, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_ip
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_ip
     *
     * @mbggenerated
     */
    int insert(TerminalIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_ip
     *
     * @mbggenerated
     */
    int insertSelective(TerminalIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_ip
     *
     * @mbggenerated
     */
    TerminalIp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_ip
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TerminalIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_ip
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TerminalIp record);

    TerminalIp selectByIpAndPort(@Param("ip")String ip, @Param("port")Integer port);

    List<TerminalIp> selectAll();
}