package cn.zucc.debug.macore.model.mapper;

import cn.zucc.debug.frame.ssm.BaseMapper;
import cn.zucc.debug.macore.model.pojo.TerminalAttr;

import java.util.List;

public interface TerminalAttrMapper extends BaseMapper<TerminalAttr, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_attr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_attr
     *
     * @mbggenerated
     */
    int insert(TerminalAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_attr
     *
     * @mbggenerated
     */
    int insertSelective(TerminalAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_attr
     *
     * @mbggenerated
     */
    TerminalAttr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TerminalAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TerminalAttr record);

    List<TerminalAttr> selectByTerminalId(Integer terminalId);
}